name: FancyMagic
main: com.lerdorf.fancymagic.FancyMagic
version: 1.0
bootstrapper: com.lerdorf.fancymagic.FancyMagicBootstrap
api-version: '1.21.7'
commands:
  magic:
    description: Get a spell scroll
    usage: /<command> <spell name>
    permission: fancymagic.magic